//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Прокат
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Услуги = new HashSet<Услуги>();
        }
    
        public int Код { get; set; }
        public string Код_заказа { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<System.TimeSpan> Время_заказа { get; set; }
        public Nullable<int> Код_клиента { get; set; }
        public string Статус { get; set; }
        public Nullable<System.DateTime> Дата_закрытия { get; set; }
        public Nullable<double> Время_проката_ч { get; set; }
    
        public virtual Клиенты Клиенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Услуги> Услуги { get; set; }
    }
}
